name: TPSLimiter
author: game.crash
description: A simple plugin for the TPS control of a Server, with a bit more customization.
depend:
  - 'LuckPerms'
  - 'Spark'
version: ${project.version}
main: me.gamecrash.tpslimiter.TPSLimiter
api-version: '1.21'
permissions:
  tpslimiter:
    description: Shows current tps.
    default: true
  tpslimiter.info:
    description: Shows information about the current state.
    default: true
  tpslimiter.set:
    description: Allows the player to set the tps. If no value is specified, the maximum value will be used.
    default: false
    children:
      tpslimiter.set.*:
        description: Binds the maximum tps value to the specified integer. There will only be the limit specified in the config, if this isnt set or it has * as value.
        default: false
    tpslimiter.step:
      description: Allows the player to step a specified amount of tps forward. If no value is specified, the maximum value will be used.
      default: false
      children:
        tpslimiter.step.*:
          description: Binds the maximum step value to the specified integer. There will only be the limit specified in the config, if this isnt set or it has * as value.
          default: false
  tpslimiter.freeze:
    description: Allows the player to freeze the tps.
    default: false
  tpslimiter.unfreeze:
    description: Allows the player to unfreeze the tps.
    default: false
  tpslimiter.reload:
    description: Allows the player to reload the configuration.
    default: false
  tpslimiter.reset:
    description: Allows the player to reset any tps-related changes.
    default: false
  tpslimiter.force:
    description: Allows the player to bypass any restrictions whatsoever.
    default: false
  tpslimiter.getNotifications:
    description: Allows the player to get the notifications if someone changed values.
    default: true