name: TPSLimiter
author: game.crash
depend:
  - 'LuckPerms'
version: '1.0-SNAPSHOT'
main: me.gamecrash.tpslimiter.TPSLimiter
api-version: '1.21'
permissions:
  tps:
    description: Shows current tps.
    default: true

  tps.set:
    description: Allows the player to set the tps.
    default: false
    children:
      tps.set.*:
        description: Binds the maximum tps value to the specified integer. There will be no limit, if this isnt set or it has * as value.
        default: false
  tps.freeze:
    description: Allows the player to freeze the tps.
    default: false
  tps.unfreeze:
    description: Allows the player to unfreeze the tps.
    default: false
  tps.reload:
    description: Allows the player to reload the configuration.
    default: false
  tps.reset:
    description: Allows the player to reset any tps-related changes.
    default: false